### ISSUE TITLE
add food to a menu

### ISSUE THREAD

**Issue by JSmith989** [nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard#90]
# User Story
user wants food added to a menu 

# Acceptance Criteria
when the user goes to the food page, they should see a menu for snacks and a menu for meals

# Dev Notes
create dropdown for snacks and meals

**Comment by willkotheimer** [comment]
This story has been split out. Remaining tasks are:
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/96
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/97
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/98
